### ISSUE TITLE
Tracking compatibility with original httpbin

### ISSUE THREAD

**Issue by mccutchen** [mccutchen/go-httpbin#91]
Let's use this as a place to track compatibility with original httpbin:

- [ ] https://github.com/mccutchen/go-httpbin/issues/15
- [ ] https://github.com/mccutchen/go-httpbin/issues/37
- [ ] https://github.com/mccutchen/go-httpbin/pull/89
- [ ] https://github.com/mccutchen/go-httpbin/issues/90

**Comment by sonbui00** [comment]
I got a different response 

```
Original
 curl https://httpbin.org/response-headers\?access_token\=faketoken\&token_type\=Bearer   
{
  "Content-Length": "128", 
  "Content-Type": "application/json", 
  "access_token": "faketoken", 
  "token_type": "Bearer"
}

go-httpbin
 curl http://httpbin:9100/response-headers\?access_token\=faketoken\&token_type\=Bearer  
{
  "access_token": [
    "faketoken"
  ],
  "token_type": [
    "Bearer"
  ]
}
```

**Comment by mccutchen** [comment]
Good catch, thanks. I think we should include both Content-Length and Content-Type to match original httpbin.

Are you interested in opening an issue for that specific feature and/or opening a pull request to implement it? (An interesting question is what should happen if the request specifies different, incorrect values for those two headers; might be worth seeing how httpbin.org handles those cases.)

But, to be clear, go-httpbin will continue to serialize header values (and form values and any other “zero or more” values inherent to HTTP) as JSON arrays for consistency, where original httpbin serializes them as single scalar values, arrays, or comma-separated strings, depending on the endpoint and incoming request parameters.

**Comment by bleggett** [comment]
it should be noted that `httpbin` returns the following body for 418

```
        -=[ teapot ]=-

           _...._
         .'  _ _ `.
        | ."` ^ `". _,
        \_;`"---"`|//
          |       ;/
          \_     _/
            `"""`
```

and this implementation does not.

As per https://www.rfc-editor.org/rfc/rfc2324#section-2.3.2 this is strictly speaking in compliance with the RFC, but it is a difference in behavior.

**Comment by mccutchen** [comment]
@bleggett please report that as a separate issue (or skip the separate issue and open a pull request to fix it).
